### ISSUE TITLE
Support für Instagram

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-oembed#1]
Bitte ein neues Inhaltselement für Instagram-Embedding hinzufügen. https://www.instagram.com/developer/embedding/

Den Master-Branch habe ich neu geschrieben für Contao 4.7, ich weiss nicht ob du bereits mit den Fragments gearbeitet hast? Im Prinzip benötigt es aus meiner Sicht drei Dinge für Instagram
 1. einen zusätzlichen Hook Listener der wie Twitter beim `save/onsubmit_callback` den Embedd-Code in `tl_content.html` speichert
 2. Einen neuen Service in der `services.yml` der wieder denselben Controller verwendet, aber einen eigenen Name (`type`) hat.
 3. Ein Template dass wie der Type benannt ist, aber vermutlich fast identisch wie die Twitter-Templates sein kann.

Bei Unklarheiten gerne fragen oder telefonieren :-)

**Comment by aschempp** [comment]
Noch ein Hinweis, bei dieser (neuen) Extension haben wir kein Git Flow, also einfach im Master Branch committen 😊

**Comment by richardhj** [comment]
Implemented in cb2e95ba679e6c7c6cf86da1a4a6bac0b716bf75.

Ich brauch Feedback für den Parameter `omitscript` (siehe https://www.instagram.com/developer/embedding/).

> The embed code contains a preview HTML code and a reference to the Instagram **embeds.js** JavaScript library. When the library is loaded, it scans the page for the HTML code and generates the fully rendered post.  
If you want to load the library separately from the HTML code, you can call the oEmbed endpoint with the **omitscript** parameter. This is useful for websites that want to handle the loading of the embeds.js script by themselves. To manually initialize the embed code, you can then call the JavaScript function **instgrm.Embeds.process()**.

Wir haben folgende Optionen:
1. Den Parameter `omitscript` nicht unterstützen. Instagram-Posts werden standardmäßig korrekt angezeigt.
2. Den Parameter konfigurierbar machen: <img width="1156" alt="screen shot 2019-03-06 at 12 12 08" src="https://user-images.githubusercontent.com/1284725/53877304-1bfd9e00-4009-11e9-8663-7f02a432a745.png">
Geht einfach, finde ich aber schwierig, da die wenigsten was damit anfangen können, und insb. Redakteure nichts damit zu tun haben sollen. Wenn `omitscript=1`, und das JS nicht eingebunden, sieht der Post übrigens so aus: <img width="663" alt="screen shot 2019-03-06 at 12 13 32" src="https://user-images.githubusercontent.com/1284725/53877410-60893980-4009-11e9-8668-f01772b3b256.png">
3. Intern automtatisch `omitscript=1` übermitteln, und das JS per Template laden.

**Comment by aschempp** [comment]
Ich würde Variante 3 machen, so machen wir es auch bei Twitter.
