### ISSUE TITLE
README aktualisieren

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-oembed#2]
Die Readme-Datei ist ziemlich veraltet und enthält noch Infos der initialen Version welche nur Twitter konnte, und vermutlich sogar bevor es die Managed Edition gab.

Ich denke den Install-Teil mit Composer könnten wir irgendwie schlauer machen, sodass wir eher beschreiben dass man (auch) per Manager installieren kann. Vielleicht hast du hier bei anderen Bundles schon mal gesehen wie das jemand beschreibt, sodass wir eine Art "Standard" für alle unsere Bundles erfinden könnten?

**Comment by richardhj** [comment]
Die Standard-installation gibt es ja nicht mehr, dann kann der Part mit dem Kernel ja echt weg.
Sonst könnte man folgendes machen: (View in GitHub).

<details>
  <summary>Click to expand!</summary>
  
### Step 1: Download the Bundle

Open a command console, enter your project directory and execute the
following command to download the latest stable version of this bundle:

```bash
$ composer require terminal42/contao-oembed "^1.0@dev"
```

This command requires you to have Composer installed globally, as explained
in the [installation chapter](https://getcomposer.org/doc/00-intro.md)
of the Composer documentation.

### Step 2: Enable the Bundle

Then, enable the bundle by adding it to the list of registered bundles
in the `app/AppKernel.php` file of your project:

```php
<?php
// app/AppKernel.php

// ...
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = array(
            // ...

            new Terminal42\OEmbedBundle\Terminal42OEmbedBundle(),
        );

        // ...
    }

    // ...
}
```
</details>

**Comment by aschempp** [comment]
Ich seh jetzt auf den ersten Blick keinen Unterschied zum aktuellen 😄 
Aus meiner Sicht müsste beim Download etwas stehen dass man dies entweder über den Contao Manager oder per Composer machen kann. Und bei "Enable the Bundle" eher sowas wie "wird in der Contao Managed Edition" automatisch aktiviert, ansonsten lies das Symfony Handbuch? 😇

**Comment by richardhj** [comment]
Ich hatte schon was hochgeladen, und denke, das wichtigste ist drin 🤔 https://github.com/terminal42/contao-oembed/blob/master/README.md

**Comment by aschempp** [comment]
👍
