### ISSUE TITLE
Composer requirements could not be resolved 

### ISSUE THREAD

**Issue by Metis77** [terminal42/contao-oembed#4]
In Contao 4.9.9 & using Contao Manager this cant be installed:

```
$ /opt/plesk/php/7.4/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=UTC /var/www/vhosts/derhaeuptling.com/site_contao/web/contao-manager.phar.php composer update terminal42/contao-oembed contao/conflicts --with-dependencies --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for terminal42/contao-oembed ^1.0 -> satisfiable by terminal42/contao-oembed[1.0.0].
    - Conclusion: remove php-http/httplug 2.2.0
    - Conclusion: don't install php-http/httplug 2.2.0
    - terminal42/contao-oembed 1.0.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v1.1.0, 2.2.0].
    - Can only install one of: php-http/httplug[v1.0.0, 2.2.0].
    - Installation request for php-http/httplug (locked at 2.2.0) -> satisfiable by php-http/httplug[2.2.0].
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
# Process terminated with exit code 2
# Result: Misuse of shell builtins
```

**Comment by aschempp** [comment]
it looks like an extension you already installed is requiring `php-http/httplug` version 2.2, which is incompatible with this extension at the moment.

**Comment by Metis77** [comment]
> it looks like an extension you already installed is requiring php-http/httplug version 2.2, which is incompatible with this extension at the moment.

must be contao itself.
Just gave it a retry with fresh contao:

`composer create-project contao/managed-edition . 4.9`
than
`composer require terminal42/contao-oembed`

same error:
<img width="851" alt="Bildschirmfoto 2020-11-10 um 10 06 28" src="https://user-images.githubusercontent.com/1408361/98652913-9f25da00-233c-11eb-986b-ab52392a08e6.png">

**Comment by aschempp** [comment]
looks like you're right 😞 interestingly I didn't have that problem in my installation, neither did @leofeyer on contao.org 🤔 

```
$ composer why php-http/httplug 
php-http/client-common  2.3.0  requires  php-http/httplug (^2.0)  

$ composer why php-http/client-common
friendsofsymfony/http-cache  2.9.2  requires  php-http/client-common (^1.1.0 || ^2.0)  

$ composer why friendsofsymfony/http-cache
contao/contao                       4.9.x-dev  requires  friendsofsymfony/http-cache (^2.6)  
friendsofsymfony/http-cache-bundle  2.9.0      requires  friendsofsymfony/http-cache (^2.6)  
```

**Comment by aschempp** [comment]
While trying to upgrade this compatibility, I found out that it is most likely only a problem on your side. Contao and Symfony both work with version 1 of httplug. I guess you need to run a full `composer update` if you want to install the extension (or at least update Contao at the same time).

**Comment by aschempp** [comment]
Release 1.1.0 no longer requires http-plug
