### ISSUE TITLE
Fehler "Ungültige Instagram-URL (HTTP Status 400)" beim Speichern

### ISSUE THREAD

**Issue by heimseiten** [terminal42/contao-oembed#7]
Bei einer frischen Contao 4.13 Installation ohne Erweiterungen, außer contao-oembed, kommt beim Speichern des Inhaltselements "Instagram Post" die Fehlermeldung "Ungültige Instagram-URL (HTTP Status 400)" und es wird nicht gespeichert. 

URL mit "https://www." bspw. https://www.instagram.com/p/CxOaqDJy6rL

Habe auch schon versucht ein facebook_token in die config.yml zu schreiben, ohne Erfolg.

**Comment by aschempp** [comment]
> Habe auch schon versucht ein facebook_token in die config.yml zu schreiben, ohne Erfolg.

Daran wird es aber sehr wahrscheinlich liegen, die Standard App gibt es bei Facebook nicht mehr. Hast du den Cache gelöscht nach dem konfigurieren des Tokens?

**Comment by heimseiten** [comment]
Danke. Habe es erst ohne facebook_token mit einer ganz frischen Contao-Installation probiert. Ohne Erfolg.

**Comment by aschempp** [comment]
Ohne facebook_token kann es wie gesagt nicht funktionieren …
